// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2648.CommBase2013;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeft;
    public static SpeedController driveTrainRight;
    public static RobotDrive driveTrainRobotDrive21;
    public static SpeedController shooterShoot1;
    public static SpeedController shooterShoot2;
    public static SpeedController feederFeed;
    public static DigitalInput sensorsSwitch1;
    public static DoubleSolenoid pneumaticsHanger1;
    public static DoubleSolenoid pneumaticsHanger2;
    public static DoubleSolenoid pneumaticsShifter;
    public static Compressor pneumaticsCompressor;
    public static SpeedController greenWheelGreenWheel;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeft = new Talon(1, 1);
	LiveWindow.addActuator("DriveTrain", "Left", (Talon) driveTrainLeft);
        
        driveTrainRight = new Talon(1, 2);
	LiveWindow.addActuator("DriveTrain", "Right", (Talon) driveTrainRight);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainLeft, driveTrainRight);
	
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);
        
        shooterShoot1 = new Victor(1, 3);
	LiveWindow.addActuator("Shooter", "Shoot1", (Victor) shooterShoot1);
        
        shooterShoot2 = new Victor(1, 4);
	LiveWindow.addActuator("Shooter", "Shoot2 ", (Victor) shooterShoot2);
        
        feederFeed = new Victor(1, 5);
	LiveWindow.addActuator("Feeder", "Feed", (Victor) feederFeed);
        
        sensorsSwitch1 = new DigitalInput(1, 1);
	LiveWindow.addSensor("Sensors", "Switch1", sensorsSwitch1);
        
        pneumaticsHanger1 = new DoubleSolenoid(1, 1, 2);      
	
        
        pneumaticsHanger2 = new DoubleSolenoid(1, 3, 4);      
	
        
        pneumaticsShifter = new DoubleSolenoid(1, 5, 6);      
	
        
        pneumaticsCompressor = new Compressor(1, 2, 1, 1);
	
        
        greenWheelGreenWheel = new Victor(1, 6);
	LiveWindow.addActuator("Green Wheel", "GreenWheel", (Victor) greenWheelGreenWheel);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
