// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2648.CommBase2013.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 * This command is of a special type. Called a CommandGroup, these are structures of other commands
 * that are supposed to run in series or at the same time. Or both really, depending on what you 
 * have to do. This command group is specifically used for Autonomous, but is also available for
 * auto firing during the Teleoperated period. You can see this either in the OI class, or in robot
 * builder.
 */
public class AutoGroup extends CommandGroup {
    
    public  AutoGroup() {
      
        
        
        addParallel(new GoShoot());//Start shooter
        addSequential(new SitWait(2.75));//3.75 = too high, 2.00 = too low
        addParallel(new LaunchStart());//Fire 1
        addSequential(new SitWait(.8));
        addParallel(new LaunchStop());//Stop Fire 1
        addSequential(new SitWait(1.4));
        addParallel(new LaunchStart());//Fire 2
        addSequential(new SitWait(.8));
        addParallel(new LaunchStop());//Stop Fire 2
        addSequential(new SitWait(1.4));
        addParallel(new LaunchStart());//Fire 3
        addSequential(new SitWait(.8));
        addParallel(new LaunchStop());//Stop Fire 3
        addSequential(new SitWait(1));
        addParallel(new StopShoot());//Stop shooter
    
    }
}
