// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2648.CommBase2013.subsystems;
import org.usfirst.frc2648.CommBase2013.RobotMap;
import org.usfirst.frc2648.CommBase2013.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2648.CommBase2013.Robot;
/**
 * This class represents the metal feeder for the frisbees. THIS IS NOT THE VEX MOTOR. That is
 * the Vex class that is also listed as a subsystem. Remember that you should be using the feed
 * SpeedController representation, do not try to grab the RobotMap controller, use what is declared
 * in this class only.
 */
public class Feeder extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController feed = RobotMap.feederFeed;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new StopFeed());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        /*
         * The default command is StopFeed because we obviously don't want the feeder to just spin
         * and spin and spin.
         */
    }
    /*
     * This is a little different compared to some other commands, the feeders speed is not a
     * constant. Whereever it is called is where the speed is set.
     */
    public void feed(double speed)
    {
        feed.set(speed);
    }
    /*
     * Stops the feeder, should always have one of these for every motor based subsystem.
     */
    public void stop()
    {
        feed.set(0);
    }
    
}
